tgchannel:
  - https://t.me/univstar
  - https://t.me/iosfulishare
  - https://t.me/hkaa0
  - https://t.me/kxswa
  - https://t.me/dingyue_Center
  - https://t.me/vpnhat
  - https://t.me/baipiao01
  - https://t.me/freekankan
  - https://t.me/allporter
  - https://t.me/miaomua
  - https://t.me/jokersfantastichome
  - https://t.me/TGxChina
  - https://t.me/go4sharing
  - https://t.me/wbnet
  - https://t.me/Jsnzk
  - https://t.me/gulaiguq_baipiao2
  - https://t.me/iunsw
  - https://t.me/fffffx2
  - https://t.me/zqfxpd
  - https://t.me/BmFt1
  - https://t.me/maxshare
  - https://t.me/bamboo_vpn
  - https://t.me/baipiaob
  - https://t.me/airproxies
  - https://t.me/asjdxm
  - https://t.me/yaney_01
  #下面是自己添加的，好像都是分享的节点信息，订阅源抓不到
  - https://t.me/v2list     #分享的是节点信息，https://fanqiangdang.com提供
  - https://t.me/freev2rays
  - https://t.me/vmess_tg
  - https://t.me/freebaipiao
  - https://t.me/dafeiji100
  - https://t.me/mftizi
  - https://t.me/nodesharing
  - https://t.me/ssrsub
  - https://t.me/ssrList
  - https://t.me/aifenxiang2020
  - https://t.me/p2psharing
  - https://t.me/app_jiedian
  - https://t.me/sharingnode
  - https://t.me/WangCai_1
